In [8]:
import numpy as np
x = np.array([[1, 2, 3],[1, 2, 3]])



In [34]:
print('ndim: ', x.ndim)
print('shape: ', x.shape)
print('size: ', x.size)
print('dtype: ', x.dtype)


ndim:  2
shape:  (2, 3)
size:  6
dtype:  int64


In [76]:
A = np.arange(1,13).reshape(3,4)
print(A)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [77]:
A[:2,:2]

array([[1, 2],
       [5, 6]])

In [78]:
A[:,2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [79]:
A[A > 6] = -1
A

array([[ 1,  2,  3,  4],
       [ 5,  6, -1, -1],
       [-1, -1, -1, -1]])

In [38]:
X = np.genfromtxt('iris.csv', delimiter=',', usecols=(0, 1, 2, 3), dtype=float)
y = np.genfromtxt('iris.csv', delimiter=',', usecols=4, dtype=str)


In [44]:
print('data types of X: ', X.dtype)
print('data types of y: ', y.dtype)
print('shape of X: ', X.shape)
print('shape of y: ', y.shape)


data types of X:  float64
data types of y:  <U15
shape of X:  (150, 4)
shape of y:  (150,)


In [84]:
mu = X.mean(axis=0)
std = X.std(axis=0)
features = ['sepal length', 'sepal width', 'petal length', 'petal width']
print(features)
print(mu)
print(std)

['sepal length', 'sepal width', 'petal length', 'petal width']
[5.84333333 3.054      3.75866667 1.19866667]
[0.82530129 0.43214658 1.75852918 0.76061262]


In [88]:
species = np.unique(y)
features = ['sepal length', 'sepal width', 'petal length', 'petal width']

for s in species:
    means = X[y == s].mean(axis=0)
    print(f" Mean values for {s}:")
    for f, m in zip(features, means):
        print(f"  • {f.capitalize()}: {m:.2f}")

for s in species:
    stds = X[y == s].std(axis=0)
    print(f" Std values for {s}:")
    for f,s in zip(features, stds):
        print(f" • {f.capitalize()}: {s:.2f}")

 Mean values for Iris-setosa:
  • Sepal length: 5.01
  • Sepal width: 3.42
  • Petal length: 1.46
  • Petal width: 0.24
 Mean values for Iris-versicolor:
  • Sepal length: 5.94
  • Sepal width: 2.77
  • Petal length: 4.26
  • Petal width: 1.33
 Mean values for Iris-virginica:
  • Sepal length: 6.59
  • Sepal width: 2.97
  • Petal length: 5.55
  • Petal width: 2.03
 Std values for Iris-setosa:
 • Sepal length: 0.35
 • Sepal width: 0.38
 • Petal length: 0.17
 • Petal width: 0.11
 Std values for Iris-versicolor:
 • Sepal length: 0.51
 • Sepal width: 0.31
 • Petal length: 0.47
 • Petal width: 0.20
 Std values for Iris-virginica:
 • Sepal length: 0.63
 • Sepal width: 0.32
 • Petal length: 0.55
 • Petal width: 0.27


In [75]:
Z = (X - X.mean(axis=0)) / X.std(axis=0)
m = Z.mean(axis=0)
std = Z.std(axis=0)