In [18]:
import numpy as np



In [20]:
n = 2 
N = 11

A = np.array([[0.835, 0.667],[0.333, 0.266]])
b_star = np.array([0.168, 0.067])

B = []

for i in range(0,N):
    B.append(b_star - 0.001 + (i - 1) * 0.0002)

X = []

for i in range (0,N):
    X.append(np.linalg.solve(A,B[i]))

normres = []

for i in range (0,N):
    normres.append(np.linalg.norm(A * X[i] - B[i]))

np.linalg.cond(A)

np.float64(1323758.9999477856)

In [69]:

np.random.seed(1)
n = 5
N = 10


A = np.random.rand(n,n)

e = np.ones(n)
b = np.matmul(A,e)

B = np.zeros((N,n))

epsilon

for i in range(0,N):
    epsilon = np.random.rand(n)
    B[i] = b + epsilon

d = np.random.rand(n)
D = np.diag(d)

print(f' the solution is :', np.linalg.solve(A,b))
print(f'the solution is: ', np.linalg.solve(D,b))

X = []
for i in range(0,N):
    X.append(np.linalg.solve(A,B[i]))


X

 the solution is : [1. 1. 1. 1. 1.]
the solution is:  [9.59485374 1.68164885 6.36742001 2.64373811 5.02913529]


[array([-0.14572898,  3.35642506,  1.08995417, -0.28158098,  1.42562896]),
 array([1.96101906, 0.06466138, 1.23193446, 2.31342478, 0.82426895]),
 array([-0.11116145,  1.68517699,  1.55276769,  1.80889757,  1.27750391]),
 array([-4.87615178,  7.09540327,  5.89571382, -1.74589826,  0.17067691]),
 array([-3.56263901,  4.8364547 ,  4.50426062, -0.29231967,  0.84621836]),
 array([-0.00535572,  1.48064366,  2.13196126,  1.06701892,  1.49068928]),
 array([0.99969917, 0.98388834, 1.88915653, 0.9561588 , 1.53317485]),
 array([-0.15480973,  1.79255604,  2.6738093 ,  1.35391119,  0.35830619]),
 array([-1.11475062,  3.42702856,  3.76827012,  0.067883  ,  0.66637481]),
 array([-1.38606731,  4.60948715,  3.32909029, -1.04333647,  0.42723435])]

In [51]:
np.size(b)

5